### ISSUE TITLE
CSS Comments

### ISSUE THREAD

**Issue by sakshamrai101** [sakshamrai101/sp24-cse110-lab3#11]
## Issue Description:
Add some css comments for clarity and description. 

## Task-List to Resolve Issue:
- [ ] comments added for custom variables.  
- [ ] comments added for structural elements (header, main/body, footer)
- [ ] comments added for basic styling 
- [ ] comments added navbar and media queries styling
