### ISSUE TITLE
Meeting Minutes: Design Changes 1

### ISSUE THREAD

**Issue by sakshamrai101** [sakshamrai101/sp24-cse110-lab3#3]
## Issue Description:
Issue to add styling to index.html page. 

## Task List:
- [ ] Add basic styling to the header, footer and main sections of the file. 
- [ ] Add basic styling to the navigation tab and add clickable references to other sections of the page. 
- [ ] Add separate styling to each of the 4 sections: "details", "agenda", "notes" and "decisions" (basic padding, border, margin, display style etc)
- [ ] Add media queries for screen size compatibility.
