### ISSUE TITLE
Form Styling

### ISSUE THREAD

**Issue by sakshamrai101** [sakshamrai101/sp24-cse110-lab3#7]
## Issue Description:
Add some basic styling to the feedback form in index.html. 

## Task-List to Resolve Issue:
- [ ] Add padding, change color and add hovering effect on the submit button.
- [ ] Change Feedback - Form heading styling. 
- [ ] Changing the padding, margin and background colour of the whole form field-set. 
- [ ] Add some styling to all input field space and options.
